# -*- coding: utf-8 -*-
"""Lesson-04.2-end of Step 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fIL6b82NcOsPkVxLu49EOVPROW6gmFGP
"""

# APJC CSC Ignite 2019
# First Jupyter Notebook Exercise
# Maint : Lee Man Wei
# 2019 Sep 18


import tensorflow as tf
import matplotlib.pyplot as plt 

tf.__version__

# Loading the dataset for the Digits OCR
mnist = tf.keras.datasets.mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

print("Training data")
print(len(X_train))
print(X_train.shape)

print(len(y_train))
print(y_train.shape)

print("Testing Data")
print(len(X_test))
print(X_test.shape)

print(len(y_test))
print(y_test.shape)

X_train[3]

y_train[3]

# Let's visualise how the train data looks like
index = 3
 
pred = X_train[index]
pred = pred.reshape([28, 28]);
plt.gray()
plt.imshow(pred)
plt.show()

print("Tagged digit: ", y_train[index])